/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import apoio.GemaMsg;
import daos.FornecedorDao;
import java.awt.Color;
import javax.swing.JOptionPane;
import negocio.Fornecedor;
import persistencia.IDAO_T;

/**
 *
 * @author XorNOTE
 */
public class IjfFornecedor extends javax.swing.JInternalFrame {

    int idFornecedor;
    Fornecedor fornecedor;
    boolean edit;

    /**
     * Creates new form IjfFornecedor
     */
    public IjfFornecedor(boolean edit) {
        this.edit = edit;
        initComponents();
        fornecedor = new Fornecedor();
        TxRazao.setBackground(Color.YELLOW);
        idFornecedor = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxRazao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxFantasia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxCidade = new javax.swing.JTextField();
        TxUf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtnFechar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnDeletar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        TxCnpj = new javax.swing.JFormattedTextField();
        TxIe = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setTitle("Fornecedor");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Fornecedor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Razão Social");

        jLabel2.setText("Nome Fantasia");

        jLabel3.setText("CNPJ");

        jLabel4.setText("I.E.");

        jLabel5.setText("Endereço");

        jLabel6.setText("Cidade");

        jLabel7.setText("UF");

        BtnFechar.setText("Fechar");
        BtnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFecharActionPerformed(evt);
            }
        });

        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnDeletar.setText("Deletar");
        BtnDeletar.setEnabled(false);
        BtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.setEnabled(false);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        try {
            TxCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCnpjActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxRazao)
                    .addComponent(TxFantasia)
                    .addComponent(TxEndereco)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxCidade)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(TxUf, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnFechar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 239, Short.MAX_VALUE))
                            .addComponent(TxCnpj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxIe)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(269, 269, 269)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxIe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFechar)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnDeletar)
                    .addComponent(BtnCancelar)
                    .addComponent(btnPesquisar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_BtnFecharActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        if (!TxRazao.getText().trim().isEmpty()) {
            FornecedorDao dao = new FornecedorDao();

            fornecedor.setRazaoSocial(TxRazao.getText());
            fornecedor.setNomeFantasia(TxFantasia.getText());
            fornecedor.setCnpj(TxCnpj.getText());
            fornecedor.setIe(TxIe.getText());
            fornecedor.setEndereco(TxEndereco.getText());
            fornecedor.setCidade(TxCidade.getText());
            fornecedor.setEstado(TxUf.getText());

            String r = dao.salvar(fornecedor);

            if (r == null) {
                JOptionPane.showMessageDialog(null, GemaMsg.salvo("Fornecedor"));
                limpar();
                fornecedor = new Fornecedor();
                preencher();
                BtnDeletar.setEnabled(false);
                BtnCancelar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, GemaMsg.erroSalvar("Fornecedor") + "\n\n" + r);
            }
        } else {
            JOptionPane.showMessageDialog(null, GemaMsg.campoVazio());
        }
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void TxCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCnpjActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        Fornecedor fornecedor = (Fornecedor) pesquisar(new FornecedorDao());

        if(fornecedor != null){
            this.fornecedor = fornecedor;
        }
        preencher();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        limpar();
        fornecedor = new Fornecedor();
        preencher();
        BtnDeletar.setEnabled(false);
        BtnCancelar.setEnabled(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletarActionPerformed
        FornecedorDao dao = new FornecedorDao();
        String r = dao.excluir(fornecedor.getIdFornecedor());

        if (r == null) {
            JOptionPane.showMessageDialog(null, GemaMsg.deletado("Fornecedor"));
            limpar();
            fornecedor = new Fornecedor();
            preencher();
            BtnDeletar.setEnabled(false);
            BtnCancelar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, GemaMsg.erroDeletado("Fornecedor") + "\n\n" + r);
        }
    }//GEN-LAST:event_BtnDeletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnDeletar;
    private javax.swing.JButton BtnFechar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JTextField TxCidade;
    private javax.swing.JFormattedTextField TxCnpj;
    private javax.swing.JTextField TxEndereco;
    private javax.swing.JTextField TxFantasia;
    private javax.swing.JFormattedTextField TxIe;
    private javax.swing.JTextField TxRazao;
    private javax.swing.JTextField TxUf;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private Object pesquisar(IDAO_T t) {
        IjdPesquisaSimples pes = new IjdPesquisaSimples(new javax.swing.JFrame(), true, t);
        pes.setLocationRelativeTo(this);
        pes.setVisible(true);

        return pes.getResultado();
    }

    private void preencher() {
        idFornecedor = fornecedor.getIdFornecedor();
        TxRazao.setText(fornecedor.getRazaoSocial());
        TxFantasia.setText(fornecedor.getNomeFantasia());
        TxCnpj.setText(fornecedor.getCnpj());
        TxIe.setText(fornecedor.getIe());
        TxEndereco.setText(fornecedor.getEndereco());
        TxCidade.setText(fornecedor.getCidade());
        TxUf.setText(fornecedor.getEstado());

        if (idFornecedor != -1) {
            BtnCancelar.setEnabled(true);
            BtnDeletar.setEnabled(true);
        }

    }

    private void limpar() {
        TxRazao.setText("");
        TxRazao.requestFocus();
        TxFantasia.setText("");
        TxCnpj.setText("");
        TxIe.setText("");
        TxEndereco.setText("");
        TxCidade.setText("");
        TxUf.setText("");
    }

}
