/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import apoio.Data;
import daos.FerramentaDao;
import daos.FuncionarioDao;
import daos.PDLDao;
import daos.ProdutoMaterialDao;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import negocio.Ferramenta;
import negocio.Funcionario;
import negocio.ItemPDL;
import negocio.PDL;
import negocio.ProdutoMaterial;
import persistencia.IDAO_T;

/**
 *
 * @author XorNOTE
 */
public class IjfPDL extends javax.swing.JInternalFrame {

    private boolean edit; //Se for TRUE está em modo de edição, se for FALSE é um novo lançamento.
    private PDL pdl;

    //Pack Inserir Lançamento
    Funcionario funcLanc;
    ProdutoMaterial prodLanc;
    private int indexItem;
    private int idItem;
    ArrayList<Integer> itensDeletar;

    //Pack Abertura
    Data dataAbertura = new Data(0);
    Funcionario funcAbertura;
    Ferramenta ferraAbertura;

    //Pack Fechamento
    Data dataFechamento = new Data(0);
    String motivoDevolucao;

    /**
     * Creates new form IjfPDL
     */
    public IjfPDL() {
        initComponents();
        edit = false;
    }

    public IjfPDL(boolean e, PDL pdl) {
        initComponents();
        edit = e;
        this.pdl = pdl;
        indexItem = -1;
        idItem = -1;
        itensDeletar = new ArrayList();
        preencher();
        onOff();
        contador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DtaAbertura = new javax.swing.JLabel();
        funcionarioAbertura = new javax.swing.JLabel();
        FerramentaAbertura = new javax.swing.JLabel();
        PainelDeAba = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txCodFuncionarioLancamento = new javax.swing.JTextField();
        btnFuncionarioLancamento = new javax.swing.JButton();
        txNomeFuncionarioLancamento = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txCodProdutoLancamento = new javax.swing.JTextField();
        btnProdutoLancamento = new javax.swing.JButton();
        txNomeProdutoLancamento = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txQtdLancamento = new javax.swing.JTextField();
        jlUnidadeProdutoLancamento = new javax.swing.JLabel();
        btnInserirLançamento = new javax.swing.JButton();
        txDtaLancamento = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txCodFerramentaAbertura = new javax.swing.JTextField();
        txFeramantaNomeAbertura = new javax.swing.JTextField();
        btnPesquisarFerramentaAbertura = new javax.swing.JButton();
        txCodFuncionarioAbertura = new javax.swing.JTextField();
        btnPesquisarFuncionarioAbertura = new javax.swing.JButton();
        txNomeFuncionarioAbertura = new javax.swing.JTextField();
        btnGravarAbertura = new javax.swing.JButton();
        txtDtaAbertura = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txMotivoFechamento = new javax.swing.JTextField();
        btnGravarFechamento = new javax.swing.JButton();
        txDataFechamento = new javax.swing.JFormattedTextField();
        tituloJanela = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableItens = new javax.swing.JTable();
        btnEditarItem = new javax.swing.JButton();
        btnRemoverItem = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DtaFechamento = new javax.swing.JLabel();
        motivoFechamento = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txTotalRegistros = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txTotalFuncionario = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txTotalProducaoPC = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txTotalProduto = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txTotalProducaoKG = new javax.swing.JLabel();
        txTotalProducaoUnKg = new javax.swing.JLabel();
        txTotalProducaoUnPc = new javax.swing.JLabel();

        setTitle("Controle de Prosdução PDL");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data Abertura:");

        jLabel3.setText("Funcionário:");

        jLabel4.setText("Ferramenta:");

        DtaAbertura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DtaAbertura.setText("25/04/2018");

        funcionarioAbertura.setText("001 - Anderson Caye");

        FerramentaAbertura.setText("312 - Broca Diamantada 10mm Externa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(funcionarioAbertura))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FerramentaAbertura))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DtaAbertura)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DtaAbertura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(funcionarioAbertura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FerramentaAbertura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelDeAba.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PainelDeAba.setToolTipText("");

        jLabel27.setText("Data");

        jLabel28.setText("Funcionário");

        txCodFuncionarioLancamento.setBackground(new java.awt.Color(255, 255, 0));

        btnFuncionarioLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ask.png"))); // NOI18N
        btnFuncionarioLancamento.setPreferredSize(new java.awt.Dimension(51, 20));
        btnFuncionarioLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioLancamentoActionPerformed(evt);
            }
        });

        txNomeFuncionarioLancamento.setBackground(new java.awt.Color(255, 255, 0));

        jLabel29.setText("Produto");

        txCodProdutoLancamento.setBackground(new java.awt.Color(255, 255, 0));
        txCodProdutoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCodProdutoLancamentoActionPerformed(evt);
            }
        });

        btnProdutoLancamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ask.png"))); // NOI18N
        btnProdutoLancamento.setPreferredSize(new java.awt.Dimension(51, 20));
        btnProdutoLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoLancamentoActionPerformed(evt);
            }
        });

        txNomeProdutoLancamento.setBackground(new java.awt.Color(255, 255, 0));

        jLabel30.setText("Quantidade");

        txQtdLancamento.setBackground(new java.awt.Color(255, 255, 0));
        txQtdLancamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txQtdLancamentoKeyTyped(evt);
            }
        });

        jlUnidadeProdutoLancamento.setText("UN");

        btnInserirLançamento.setText("Inserir");
        btnInserirLançamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirLançamentoActionPerformed(evt);
            }
        });

        txDtaLancamento.setBackground(new java.awt.Color(255, 255, 0));
        try {
            txDtaLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txCodProdutoLancamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(txCodFuncionarioLancamento, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnFuncionarioLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txNomeFuncionarioLancamento))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(btnProdutoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txNomeProdutoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txQtdLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlUnidadeProdutoLancamento))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txDtaLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInserirLançamento)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(txDtaLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txCodFuncionarioLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28))
                    .addComponent(txNomeFuncionarioLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFuncionarioLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(txCodProdutoLancamento))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txNomeProdutoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(txQtdLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlUnidadeProdutoLancamento))
                    .addComponent(btnProdutoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInserirLançamento)
                .addGap(34, 34, 34))
        );

        PainelDeAba.addTab("Lançamento", jPanel4);

        jLabel14.setText("Data");

        jLabel15.setText("Ferramenta");

        jLabel16.setText("Funcionário");

        btnPesquisarFerramentaAbertura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ask.png"))); // NOI18N
        btnPesquisarFerramentaAbertura.setPreferredSize(new java.awt.Dimension(51, 20));
        btnPesquisarFerramentaAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFerramentaAberturaActionPerformed(evt);
            }
        });

        btnPesquisarFuncionarioAbertura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ask.png"))); // NOI18N
        btnPesquisarFuncionarioAbertura.setPreferredSize(new java.awt.Dimension(51, 20));
        btnPesquisarFuncionarioAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFuncionarioAberturaActionPerformed(evt);
            }
        });

        btnGravarAbertura.setText("Gravar");
        btnGravarAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarAberturaActionPerformed(evt);
            }
        });

        try {
            txtDtaAbertura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGravarAbertura))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txCodFuncionarioAbertura))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txCodFerramentaAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(txtDtaAbertura))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnPesquisarFerramentaAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txFeramantaNomeAbertura))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnPesquisarFuncionarioAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txNomeFuncionarioAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtDtaAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txFeramantaNomeAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarFerramentaAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txCodFerramentaAbertura))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txNomeFuncionarioAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarFuncionarioAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txCodFuncionarioAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGravarAbertura)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        PainelDeAba.addTab("Abertura", jPanel5);

        jLabel25.setText("Data");

        jLabel26.setText("Motivo");

        btnGravarFechamento.setText("Gravar");
        btnGravarFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarFechamentoActionPerformed(evt);
            }
        });

        try {
            txDataFechamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txDataFechamento.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txMotivoFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDataFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(393, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGravarFechamento)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txDataFechamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txMotivoFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnGravarFechamento)
                .addGap(36, 36, 36))
        );

        PainelDeAba.addTab("Fechamento", jPanel6);

        tituloJanela.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tituloJanela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloJanela.setText("CONTROLE DE PRODUÇÃO");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Registros"));

        tableItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableItens);

        btnEditarItem.setText("Editar");
        btnEditarItem.setPreferredSize(new java.awt.Dimension(75, 23));
        btnEditarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarItemActionPerformed(evt);
            }
        });

        btnRemoverItem.setText("Remover");
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRemoverItem)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverItem)
                    .addComponent(btnEditarItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(242, 242, 242))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Data Fechamento:");

        jLabel7.setText("Motivo:");

        DtaFechamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DtaFechamento.setText("--/--/----");

        motivoFechamento.setText("- - -");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DtaFechamento))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(motivoFechamento)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DtaFechamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(motivoFechamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("Total Registros");

        txTotalRegistros.setText("0");

        jLabel19.setText("Funcionários");

        txTotalFuncionario.setText("0");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Total Produção:");

        txTotalProducaoPC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txTotalProducaoPC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txTotalProducaoPC.setText("0");

        jLabel23.setText("Produtos");

        txTotalProduto.setText("0");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Total Produção:");

        txTotalProducaoKG.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txTotalProducaoKG.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txTotalProducaoKG.setText("0");

        txTotalProducaoUnKg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txTotalProducaoUnKg.setText("KG");

        txTotalProducaoUnPc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txTotalProducaoUnPc.setText("PC");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel23)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txTotalFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txTotalProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txTotalRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txTotalProducaoPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txTotalProducaoKG, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txTotalProducaoUnKg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txTotalProducaoUnPc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txTotalRegistros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txTotalFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txTotalProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txTotalProducaoKG)
                    .addComponent(txTotalProducaoUnKg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txTotalProducaoPC)
                    .addComponent(txTotalProducaoUnPc))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelDeAba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PainelDeAba, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGravarAberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarAberturaActionPerformed
        if (!txtDtaAbertura.getText().isEmpty() && funcAbertura.getNome() != null && ferraAbertura.getDescricao() != null) {
            dataAbertura = new Data(txtDtaAbertura.getText());
            pdl.setDataRetirada(dataAbertura);
            pdl.setFerramenta(ferraAbertura);
            pdl.setFuncionario(funcAbertura);
            edit = true;
            onOff();
            preencher();
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos em destaque!\nPara cadastrar a ficha é necessario que todos os campos da aba ABERTURA estejam preenchidos.");
        }
    }//GEN-LAST:event_btnGravarAberturaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvarPDL();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFuncionarioLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioLancamentoActionPerformed
        Funcionario lancamentoFuncionario = (Funcionario) pesquisar(new FuncionarioDao());
        funcLanc = lancamentoFuncionario;
        txCodFuncionarioLancamento.setText(funcLanc.getIdFuncionario() + "");
        txNomeFuncionarioLancamento.setText(funcLanc.getNome());
    }//GEN-LAST:event_btnFuncionarioLancamentoActionPerformed

    private void btnInserirLançamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirLançamentoActionPerformed
        if (txtDtaAbertura.getText().isEmpty()
                || txCodFuncionarioLancamento.getText().isEmpty()
                || txCodProdutoLancamento.getText().isEmpty()
                || txQtdLancamento.getText().isEmpty()
                || funcLanc == null
                || prodLanc == null) {
            JOptionPane.showMessageDialog(null, "Preencha os campos em destaque!\nPara realizar um lançamento na produção é precisso que todos os campos obrigatorios estejam preenchidos.");
        } else {

//            try {
            ItemPDL i = new ItemPDL();
            i.setIdItem(idItem);
            i.setData(new Data(txDtaLancamento.getText()));
            i.setFuncionario(funcLanc);
            i.setIdFicha(pdl.getIdFicha());
            i.setProduto(prodLanc);
            Double qtd = Double.parseDouble(txQtdLancamento.getText().replace(',', '.'));
            i.setQuantidade(qtd);
            
            if(indexItem == -1){
                pdl.setItens(i);
            } else {
                pdl.setItenIndex(indexItem, i);
            }
            
            preencher();
            indexItem = -1;
            idItem = -1;

            txtDtaAbertura.setText("");
            txCodFuncionarioLancamento.setText("");
            txNomeFuncionarioLancamento.setText("");
            funcLanc = null;
            txCodProdutoLancamento.setText("");
            txNomeProdutoLancamento.setText("");
            prodLanc = null;
            txQtdLancamento.setText("");

//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, "Erro ao realizar lançamento da produção!");
//            }
        }
    }//GEN-LAST:event_btnInserirLançamentoActionPerformed

    private void txCodProdutoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCodProdutoLancamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCodProdutoLancamentoActionPerformed

    private void btnProdutoLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoLancamentoActionPerformed
        ProdutoMaterial lancamentoProduto = (ProdutoMaterial) pesquisar(new ProdutoMaterialDao());
        prodLanc = lancamentoProduto;
        txCodProdutoLancamento.setText(prodLanc.getCodigo());
        txNomeProdutoLancamento.setText(prodLanc.getDescricao());
        jlUnidadeProdutoLancamento.setText(prodLanc.getUnidade());
    }//GEN-LAST:event_btnProdutoLancamentoActionPerformed

    private void txQtdLancamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txQtdLancamentoKeyTyped
        String caracteres = "0987654321,.";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txQtdLancamentoKeyTyped

    private void btnPesquisarFerramentaAberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFerramentaAberturaActionPerformed
        Ferramenta ferramenta = (Ferramenta) pesquisar(new FerramentaDao());
        ferraAbertura = ferramenta;
        txCodFerramentaAbertura.setText(ferraAbertura.getCodigo());
        txFeramantaNomeAbertura.setText(ferraAbertura.getDescricao());
    }//GEN-LAST:event_btnPesquisarFerramentaAberturaActionPerformed

    private void btnPesquisarFuncionarioAberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFuncionarioAberturaActionPerformed
        Funcionario funcionario = (Funcionario) pesquisar(new FuncionarioDao());
        funcAbertura = funcionario;
        txCodFuncionarioAbertura.setText(funcAbertura.getIdFuncionario() + "");
        txNomeFuncionarioAbertura.setText(funcAbertura.getNome());
    }//GEN-LAST:event_btnPesquisarFuncionarioAberturaActionPerformed

    private void btnGravarFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarFechamentoActionPerformed
        if (!txDataFechamento.getText().isEmpty() && !txMotivoFechamento.getText().isEmpty() ) {
            dataFechamento = new Data(txDataFechamento.getText());
            motivoDevolucao = txMotivoFechamento.getText();
            pdl.setDataDevolucao(dataFechamento);
            pdl.setMotivoDevolucao(motivoDevolucao);
            onOff();
            preencher();
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos em destaque!\nPara o fechamento da ficha é necessario que todos os campos da aba FECHAMENTO estejam preenchidos.");
        }
    }//GEN-LAST:event_btnGravarFechamentoActionPerformed

    private void btnEditarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarItemActionPerformed
        ItemPDL i = pdl.getItem(tableItens.getSelectedRow());
        System.out.println(i.getIdItem());
        if(i != null){
            indexItem = tableItens.getSelectedRow();
            idItem = i.getIdItem();
            txDtaLancamento.setText(i.getData().obterData());
            txCodFuncionarioLancamento.setText(i.getFuncionario().getIdFuncionario()+"");
            txNomeFuncionarioLancamento.setText(i.getFuncionario().getNome());
            funcLanc = i.getFuncionario();
            txCodProdutoLancamento.setText(i.getProduto().getCodigo());
            txNomeProdutoLancamento.setText(i.getProduto().getDescricao());
            prodLanc = i.getProduto();
            txQtdLancamento.setText(i.getQuantidade()+"");
        } else {
            JOptionPane.showMessageDialog(null, "Erro nenhum item selecionado.");
        }
    }//GEN-LAST:event_btnEditarItemActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        ItemPDL i = pdl.getItem(tableItens.getSelectedRow());
        if(i != null){
            indexItem = tableItens.getSelectedRow();
            itensDeletar.add(i.getIdItem());
            pdl.setItenIndexRemove(indexItem);
            preencher();
            indexItem = -1;
        } else {
            JOptionPane.showMessageDialog(null, "Erro nenhum item selecionado.");
        }
    }//GEN-LAST:event_btnRemoverItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DtaAbertura;
    private javax.swing.JLabel DtaFechamento;
    private javax.swing.JLabel FerramentaAbertura;
    private javax.swing.JTabbedPane PainelDeAba;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarItem;
    private javax.swing.JButton btnFuncionarioLancamento;
    private javax.swing.JButton btnGravarAbertura;
    private javax.swing.JButton btnGravarFechamento;
    private javax.swing.JButton btnInserirLançamento;
    private javax.swing.JButton btnPesquisarFerramentaAbertura;
    private javax.swing.JButton btnPesquisarFuncionarioAbertura;
    private javax.swing.JButton btnProdutoLancamento;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel funcionarioAbertura;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlUnidadeProdutoLancamento;
    private javax.swing.JLabel motivoFechamento;
    private javax.swing.JTable tableItens;
    private javax.swing.JLabel tituloJanela;
    private javax.swing.JTextField txCodFerramentaAbertura;
    private javax.swing.JTextField txCodFuncionarioAbertura;
    private javax.swing.JTextField txCodFuncionarioLancamento;
    private javax.swing.JTextField txCodProdutoLancamento;
    private javax.swing.JFormattedTextField txDataFechamento;
    private javax.swing.JFormattedTextField txDtaLancamento;
    private javax.swing.JTextField txFeramantaNomeAbertura;
    private javax.swing.JTextField txMotivoFechamento;
    private javax.swing.JTextField txNomeFuncionarioAbertura;
    private javax.swing.JTextField txNomeFuncionarioLancamento;
    private javax.swing.JTextField txNomeProdutoLancamento;
    private javax.swing.JTextField txQtdLancamento;
    private javax.swing.JLabel txTotalFuncionario;
    private javax.swing.JLabel txTotalProducaoKG;
    private javax.swing.JLabel txTotalProducaoPC;
    private javax.swing.JLabel txTotalProducaoUnKg;
    private javax.swing.JLabel txTotalProducaoUnPc;
    private javax.swing.JLabel txTotalProduto;
    private javax.swing.JLabel txTotalRegistros;
    private javax.swing.JFormattedTextField txtDtaAbertura;
    // End of variables declaration//GEN-END:variables

    private void onOff() {
        //Verifica se a chamada é para um novo lançamento ou uma edição.
        if (edit) {
            
            btnEditarItem.setEnabled(true);
            btnRemoverItem.setEnabled(true);
            btnSalvar.setEnabled(true);
            
            txtDtaAbertura.setEnabled(false);
            txCodFerramentaAbertura.setEnabled(false);
            txCodFuncionarioAbertura.setEnabled(false);
            txFeramantaNomeAbertura.setEnabled(false);
            txNomeFuncionarioAbertura.setEnabled(false);
            btnGravarAbertura.setEnabled(false);
            btnPesquisarFerramentaAbertura.setEnabled(false);
            btnPesquisarFuncionarioAbertura.setEnabled(false);
            PainelDeAba.setSelectedIndex(0);
            PainelDeAba.setEnabledAt(0, true);
            PainelDeAba.setEnabledAt(2, true);
            
            if (pdl.getMotivoDevolucao() != null) {
                txDataFechamento.setEnabled(false);
                txMotivoFechamento.setEnabled(false);
                btnGravarFechamento.setEnabled(false);
                btnEditarItem.setEnabled(false);
                btnRemoverItem.setEnabled(false);
                PainelDeAba.setSelectedIndex(0);
                PainelDeAba.setEnabledAt(0, false);
                PainelDeAba.setEnabledAt(1, false);
                PainelDeAba.setEnabledAt(2, false);
            }

        } else {
            //Ao criar uma nova ficha apenas a segunda aba deve ser possivel de editar.
            PainelDeAba.setEnabledAt(0, false);
            PainelDeAba.setEnabledAt(2, false);
            PainelDeAba.setSelectedIndex(1);

            btnEditarItem.setEnabled(false);
            btnRemoverItem.setEnabled(false);
            btnSalvar.setEnabled(false);

        }
    }

    private void preencher() {
        //Popular Tabela
        new PDLDao().popularTabela(tableItens, pdl.getItens());
        //Preencher Titulo tela.
        tituloJanela.setText("CONTROLE DE PRODUÇÃO");
//        btnDesabilitarFicha.setEnabled(false);
//        btnGerarFicha.setEnabled(false);
        if(pdl.getIdFicha() != -1){
            tituloJanela.setText(tituloJanela.getText() + " #" + pdl.getIdFicha());
//            btnDesabilitarFicha.setEnabled(true);
//            btnGerarFicha.setEnabled(true);
        }

        //Data de Abertuta, se ela for nula preenche com uma mascara 'falsa'.
        //Funcionario de Aberuta
        //Ferramenta
        DtaAbertura.setText("--/--/----");
        funcionarioAbertura.setText("- - -");
        FerramentaAbertura.setText("- - -");
        if (!pdl.getDataRetiradaIsEmpty()) {
            DtaAbertura.setText(pdl.getDataRetirada());
            dataAbertura = new Data( pdl.getDataRetirada() );
            funcionarioAbertura.setText(pdl.getFuncionario().getIdFuncionario() + " - " + pdl.getFuncionario().getNome());
            funcAbertura = pdl.getFuncionario();
            FerramentaAbertura.setText(pdl.getFerramenta().getCodigo() + " - " + pdl.getFerramenta().getDescricao());
            ferraAbertura = pdl.getFerramenta();
        }

        //Data de Fechamento, se ela for nula preenche com uma mascara 'falsa'.
        DtaFechamento.setText("--/--/----");
        if (!pdl.getDataDevolucaoIsEmpty()) {
            DtaFechamento.setText(pdl.getDataDevolucao());
            dataFechamento = new Data(pdl.getDataDevolucao());
        }
        //Motivo de Fechamento
        motivoFechamento.setText("- - -");
        if (pdl.getMotivoDevolucao() != null) {
            motivoFechamento.setText(pdl.getMotivoDevolucao());
            motivoDevolucao = pdl.getMotivoDevolucao();
        }

        //########### Aba Abertura
        //Data Abertura
        txtDtaAbertura.setText("");
        if (!pdl.getDataRetiradaIsEmpty()) {
            txtDtaAbertura.setText(pdl.getDataRetirada());
        }
        //Funcionario
        txCodFuncionarioAbertura.setText("");
        txNomeFuncionarioAbertura.setText("");
        if (pdl.getFuncionario().getNome() != null) {
            txCodFuncionarioAbertura.setText(pdl.getFuncionario().getIdFuncionario() + "");
            txNomeFuncionarioAbertura.setText(pdl.getFuncionario().getNome());
        }
        //Feramenta
        txCodFerramentaAbertura.setText("");
        txFeramantaNomeAbertura.setText("");
        if (pdl.getFerramenta().getDescricao() != null) {
            txCodFerramentaAbertura.setText(pdl.getFerramenta().getCodigo());
            txFeramantaNomeAbertura.setText(pdl.getFerramenta().getDescricao());
        }
        
        //########### Aba Fechamento
        //Data
        txDataFechamento.setText("");
        if (!pdl.getDataDevolucaoIsEmpty()){
            txDataFechamento.setText(pdl.getDataDevolucao());
        }
        //Motivo
        txMotivoFechamento.setText("");
        if(pdl.getMotivoDevolucao() != null){
            txMotivoFechamento.setText(pdl.getMotivoDevolucao());
        }
        contador();
    }

    private void contador() {
        Double totalProducaoPC = 0.0;
        Double totalProducaoKG = 0.0;
        int totalRegistros = pdl.getItens().size();
        int totalFuncionarios = 0;
        int totalProdutos = 0;
        TreeMap<Integer, String> func = new TreeMap();
        TreeMap<Integer, String> prod = new TreeMap();
        for (int i = 0; i < pdl.getItens().size(); i++) {
            prod.put(pdl.getItens().get(i).getProduto().getIdproduto(),
                    "[" + pdl.getItens().get(i).getProduto().getCodigo() + "] " + pdl.getItens().get(i).getProduto().getDescricao());
            func.put(pdl.getItens().get(i).getFuncionario().getIdFuncionario(),
                    pdl.getItens().get(i).getFuncionario().getNome());

            if (pdl.getItens().get(i).getProduto().getUnidade().equals("PC")) {
                totalProducaoPC += pdl.getItens().get(i).getQuantidade();
            } else if (pdl.getItens().get(i).getProduto().getUnidade().equals("KG")) {
                totalProducaoKG += pdl.getItens().get(i).getQuantidade();
            }
        }

        totalFuncionarios = func.size();
        totalProdutos = prod.size();

        txTotalFuncionario.setText(totalFuncionarios + "");
        txTotalProduto.setText(totalProdutos + "");
        txTotalRegistros.setText(totalRegistros + "");

//        DecimalFormat df = new DecimalFormat("#,###.00");
        txTotalProducaoPC.setText( /*df.format(*/totalProducaoPC + "" /*)*/);
        txTotalProducaoKG.setText( /*df.format(*/totalProducaoKG + "" /*)*/);

    }

    private Object pesquisar(IDAO_T t) {

        IjdPesquisaSimples pes = new IjdPesquisaSimples(new javax.swing.JFrame(), true, t);
        pes.setLocationRelativeTo(this);
        pes.setVisible(true);

        return pes.getResultado();
    }

    /**
     *
     * @param nivel
     */
    private void salvarPDL() {
        pdl.setDataRetirada(dataAbertura);
        pdl.setDataDevolucao(dataFechamento);
        pdl.setMotivoDevolucao(motivoDevolucao);
        pdl.setFerramenta(ferraAbertura);
        pdl.setFuncionario(funcAbertura);
        pdl.setRemoverItens(itensDeletar);

        String salvar = new PDLDao().salvar(pdl);

        if (salvar == null) {
            JOptionPane.showMessageDialog(null, "Ficha salva com sucesso.");
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao salvar a ficha.\n\n" + salvar);
        }
    }

}
