/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import apoio.Gema;
import daos.UsuarioDao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.Usuario;

/**
 *
 * @author XorNOTE
 */
public class IjfUsuarioLogin extends javax.swing.JInternalFrame {

    private UsuarioDao usuarioDao;
    private Usuario usuario;

    /**
     * Creates new form IjfUsuarioLogin
     */
    public IjfUsuarioLogin(Usuario u) {
        initComponents();
        usuario = u;
        
        atu(usuario);

        usuarioDao = new UsuarioDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnDesativar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxId = new javax.swing.JLabel();
        TxNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxUser = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxSenha = new javax.swing.JPasswordField();
        BtnEditar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txStatus = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Dados do Login");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aletar Dados Usuário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        BtnDesativar.setText("Excluir Usuário");
        BtnDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDesativarActionPerformed(evt);
            }
        });

        BtnSalvar.setText("Salvar");
        BtnSalvar.setEnabled(false);
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        TxId.setText("NULL");

        TxNome.setEnabled(false);

        jLabel3.setText("Nome");

        jLabel4.setText("Nick:");

        TxUser.setText("user");

        jLabel6.setText("Senha");

        TxSenha.setEnabled(false);

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Status:");

        txStatus.setText("res");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 90, Short.MAX_VALUE)
                        .addComponent(BtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxUser))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxId)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnDesativar))
                    .addComponent(TxSenha)
                    .addComponent(TxNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txStatus)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TxId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxUser)))
                    .addComponent(BtnDesativar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txStatus))
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnEditar)
                    .addComponent(BtnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDesativarActionPerformed
        usuarioDao.excluir(usuario.getIdusuario());
        JfLogin log = new JfLogin();
        System.exit(0);
    }//GEN-LAST:event_BtnDesativarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        BtnDesativar.setEnabled(false);
        BtnEditar.setEnabled(false);
        BtnSalvar.setEnabled(true);
        
        TxNome.setEnabled(true);
        TxSenha.setEnabled(true);
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        Usuario us = usuario;
        if (TxSenha.getText().trim().isEmpty()) {
            if (TxNome.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Preencha o campo nome!");
            } else {
                us.setNome(TxNome.getText());
                String r = usuarioDao.atualizar(us);

                if (r == null) {
                    JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso!");
                    usuario = us;
                    enabSalvar();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro a atualizar dados do usuário. \n" + r);
                }
            }
        } else {
            try {
                us.setPass(Gema.criptoSenha(TxSenha.getText()));
            } catch (Exception ex) {
                Logger.getLogger(IjfUsuarioLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (TxNome.getText().trim().isEmpty()) {

                String r = usuarioDao.atualizar(us);

                if (r == null) {
                    JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso!");
                    usuario = us;
                    enabSalvar();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro a atualizar dados do usuário. \n" + r);
                }

            } else {
                us.setNome(TxNome.getText());
                String r = usuarioDao.atualizar(us);

                if (r == null) {
                    JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso!");
                    usuario = us;
                    enabSalvar();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro a atualizar dados do usuário. \n" + r);
                }

            }
        }
        
        
        atu(usuario);
        
    }//GEN-LAST:event_BtnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnDesativar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JLabel TxId;
    private javax.swing.JTextField TxNome;
    private javax.swing.JPasswordField TxSenha;
    private javax.swing.JLabel TxUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txStatus;
    // End of variables declaration//GEN-END:variables
    private void atu (Usuario u){
        TxId.setText(u.getIdusuario() + "");
        TxUser.setText(u.getNick());
        TxNome.setText(u.getNome());
        String status="Inativo";
        if(u.isAtivo()){
            status = "Ativo";
        }
        txStatus.setText(status);
    }
    
    private void enabSalvar (){
        BtnDesativar.setEnabled(true);
        BtnEditar.setEnabled(true);
        BtnSalvar.setEnabled(false);
        
        TxNome.setEnabled(false);
        TxSenha.setEnabled(false);
    }
}
